### ISSUE TITLE
preprocess.py

### ISSUE THREAD

**Issue by gaoyiyao** [Labmem-Zhouyx/CDFSE_FastSpeech2#14]
(CDFSE) root@autodl-container-66ee44be9a-c385597c:~/CDFSE_FastSpeech2-main# python3 preprocess.py config/AISHELL3/preprocess.yaml
Processing Data ...
  0%|                                                                                                                 | 0/218 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "preprocess.py", line 19, in <module>
    preprocessor.build_from_path()
  File "/root/CDFSE_FastSpeech2-main/preprocessor/preprocessor.py", line 86, in build_from_path
    if len(pitch) > 0:
UnboundLocalError: local variable 'pitch' referenced before assignment

**Comment by gaoyiyao** [comment]
5，(CDFSE) root@autodl-container-a33f42a766-eca23369:~/CDFSE_FastSpeech# python3 preprocess.py config/AISHELL3/preprocess.yaml
Processing Data ...
0it [00:00, ?it/s]
Computing statistic quantities ...
Traceback (most recent call last):
  File "preprocess.py", line 19, in <module>
    preprocessor.build_from_path()
  File "/root/CDFSE_FastSpeech/preprocessor/preprocessor.py", line 96, in build_from_path
    pitch_mean = pitch_scaler.mean_[0]
AttributeError: 'StandardScaler' object has no attribute 'mean_'

**Comment by lareina-a** [comment]
> 5，(CDFSE) root@autodl-container-a33f42a766-eca23369:~/CDFSE_FastSpeech# python3 preprocess.py config/AISHELL3/preprocess.yaml Processing Data ... 0it [00:00, ?it/s] Computing statistic quantities ... Traceback (most recent call last): File "preprocess.py", line 19, in preprocessor.build_from_path() File "/root/CDFSE_FastSpeech/preprocessor/preprocessor.py", line 96, in build_from_path pitch_mean = pitch_scaler.mean_[0] AttributeError: 'StandardScaler' object has no attribute 'mean_'

请问这个怎么解决的呢

**Comment by xulong66** [comment]
if self.pitch_normalization:
            # 检查scaler是否已拟合
            if hasattr(pitch_scaler, 'mean_') and pitch_scaler.mean_ is not None:
                pitch_mean = pitch_scaler.mean_[0]
                pitch_std = pitch_scaler.scale_[0]
            else:
                print(f"警告: 无有效音高数据，使用默认值")
                pitch_mean, pitch_std = 0, 1  # 安全回退值
        else:
            # A numerical trick to avoid normalization...
            pitch_mean = 0
            pitch_std = 1


        # 修改后（安全版本）
        if self.energy_normalization:
            if hasattr(energy_scaler, 'mean_') and energy_scaler.mean_ is not None:
                energy_mean = energy_scaler.mean_[0]
                energy_std = energy_scaler.scale_[0]
            else:
                print("警告: 无有效能量数据，使用默认值")
                energy_mean, energy_std = 0, 1  # 安全回退。AI给的建议，再看看config里面的数据集路径等是否正确
