### ISSUE TITLE
关于libriTTS数据集

### ISSUE THREAD

**Issue by WhiteFu** [Labmem-Zhouyx/CDFSE_FastSpeech2#4]
大佬，我在网上openslr上面下载的libriTTS 的clean100数据集和你们处理好的不一样，文本和语音都对不上，是我下错了还是需要额外的处理呢？求解惑

**Comment by Labmem-Zhouyx** [comment]
你好，libriTTS我们是用的openslr上下载的数据集，关于预处理部分代码脚本和ming024/FastSpeech2也基本一致，你可以先判断下是哪一步出的问题导致文本和语音对不上。

以下是我重新处理的一些流程。

下载解压好LibriTTS数据集：

![image](https://user-images.githubusercontent.com/63361337/208362486-23268161-7e56-4a09-9ab6-b44f20e12cf7.png)

第一步：执行prepare_align.py，按照说话人目录获得文本、语音成对的lab标注和wav文件，可检查是否对应；

![image](https://user-images.githubusercontent.com/63361337/208362572-3f9db1d1-31cd-4984-8cb4-c422d8d6b218.png)

第二步：下载对齐文件TextGrid放到指定目录下，这里也可以检查下对齐结果是正常；

![image](https://user-images.githubusercontent.com/63361337/208426532-e9385be3-5d8d-4967-ade5-613683ecceea.png)
![image](https://user-images.githubusercontent.com/63361337/208425995-39931eb8-93fd-46b4-995b-cb792f56efbc.png)


第三步：执行preprocess.py，获得train-clean-100/dev-clean/test-clean.txt等文件 以及 duration/pitch/energy/mel等数据。

![image](https://user-images.githubusercontent.com/63361337/208426218-e525c963-d1bc-439d-aa5b-c09a97b2b659.png)
![image](https://user-images.githubusercontent.com/63361337/208426325-d22b233c-b3c9-48fc-9b99-0d9ca38ba319.png)

**Comment by WhiteFu** [comment]
谢谢老哥的回复
![image](https://user-images.githubusercontent.com/32156119/208594449-fac83165-2143-4416-bc46-e89e18fed5cb.png)
你们的wav是程序自动切分转换的来的吗，我对过我自己下载好的东西，我发现对应前缀的音频和文本和你们的就不太一样，比如669_129061_000001后面所有的和我对应的文本都不一致
![image](https://user-images.githubusercontent.com/32156119/208594802-80daa006-a023-4a4e-9296-f3f95e9cd818.png)
是我差了那一步呢，或者是下载的目录有错？

**Comment by WhiteFu** [comment]
而且我的音频是16K的，下载地址能提供给我一下吗，感谢

**Comment by Labmem-Zhouyx** [comment]
https://www.openslr.org/60/.

**Comment by WhiteFu** [comment]
好的，多谢哈

**Comment by lareina-a** [comment]
您好，请问LibriTTS的对齐MFA文件从哪下载呢

**Comment by lareina-a** [comment]
> 你好，libriTTS我们是用的openslr上下载的数据集，关于预处理部分代码脚本和ming024/FastSpeech2也基本一致，你可以先判断下是哪一步出的问题导致文本和语音对不上。
> 
> 以下是我重新处理的一些流程。
> 
> 下载解压好LibriTTS数据集：
> 
> ![image](https://user-images.githubusercontent.com/63361337/208362486-23268161-7e56-4a09-9ab6-b44f20e12cf7.png)
> 
> 第一步：执行prepare_align.py，按照说话人目录获得文本、语音成对的lab标注和wav文件，可检查是否对应；
> 
> ![image](https://user-images.githubusercontent.com/63361337/208362572-3f9db1d1-31cd-4984-8cb4-c422d8d6b218.png)
> 
> 第二步：下载对齐文件TextGrid放到指定目录下，这里也可以检查下对齐结果是正常；
> 
> ![image](https://user-images.githubusercontent.com/63361337/208426532-e9385be3-5d8d-4967-ade5-613683ecceea.png) ![image](https://user-images.githubusercontent.com/63361337/208425995-39931eb8-93fd-46b4-995b-cb792f56efbc.png)
> 
> 第三步：执行preprocess.py，获得train-clean-100/dev-clean/test-clean.txt等文件 以及 duration/pitch/energy/mel等数据。
> 
> ![image](https://user-images.githubusercontent.com/63361337/208426218-e525c963-d1bc-439d-aa5b-c09a97b2b659.png) ![image](https://user-images.githubusercontent.com/63361337/208426325-d22b233c-b3c9-48fc-9b99-0d9ca38ba319.png)

Checking TextGrid path: data/training_data/preprocessed_data/LibriTTS/TextGrid/121/121_127105_000043_000003.TextGrid
Does TextGrid exist for 121_127105_000043_000003? False
TextGrid not found for 121_127105_000043_000003: data/training_data/preprocessed_data/LibriTTS/TextGrid/121/121_127105_000043_000003.TextGrid
Checking TextGrid path: data/training_data/preprocessed_data/LibriTTS/TextGrid/121/121_127105_000036_000001.TextGrid
Does TextGrid exist for 121_127105_000036_000001? False这些文件没有

**Comment by gaoyiyao** [comment]
Processing Data ...
train-clean-100: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 247/247 [00:00<00:00, 1165.51it/s]
Traceback (most recent call last):
  File "preprocess.py", line 21, in <module>
    preprocessor.build_from_path() #调用预处理器实例的build_from_path方法
  File "/root/MY-CDFSE/preprocessor/preprocessor_multiset.py", line 82, in build_from_path
    for speaker in tqdm(os.listdir(dset_dir), desc=dset):
FileNotFoundError: [Errno 2] No such file or directory: '/root/MY-CDFSE/raw_data/LibriTTS/dev-clean'

有没有大神解答一下这是什么原因，为什么在python3 prepare_align.py config/LibriTTS/preprocess.yaml的时候，他没有处理完全，
